#!/bin/bash

[ "$2" != "lo" ] || exit 0

if test -f /etc/sysconfig/avahi ; then
  . /etc/sysconfig/avahi
fi

if test "$AVAHI_AUTOIPD_ENABLE" = "yes" ; then
  /usr/sbin/avahi-autoipd -k $2 2> /dev/null || exit 0
fi
